# Generated by Django 6.0.7 on 2026-08-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='event_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
