# Generated by Django 6.0.7 on 2026-08-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
