# Generated by Django 6.0.7 on 2026-08-12 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_driverprofile_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='ride_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rides', to='rides.vehicletype'),
        ),
    ]
