# Generated by Django 6.0.7 on 2026-08-17 11:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0004_alter_ride_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['user'], name='rides_ride_user_id_50af28_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['driver'], name='rides_ride_driver__850520_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['ride_type'], name='rides_ride_ride_ty_d6cae2_idx'),
        ),
    ]
