# Generated by Django 6.0.7 on 2026-08-18 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0005_ride_rides_ride_user_id_50af28_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_available', models.BooleanField(default=False)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='rides.driverprofile')),
            ],
        ),
    ]
