# Generated by Django 6.0.7 on 2026-08-18 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0006_driverlocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverlocation',
            name='is_available',
        ),
        migrations.AddField(
            model_name='driverlocation',
            name='availability_status',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('BUSY', 'Busy')], default='OFFLINE', max_length=10),
        ),
    ]
