# Generated by Django 6.0.7 on 2026-08-18 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0007_remove_driverlocation_is_available_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='driverlocation',
            index=models.Index(fields=['availability_status'], name='rides_drive_availab_e9610f_idx'),
        ),
    ]
