# Generated by Django 6.0.7 on 2026-08-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0008_driverlocation_rides_drive_availab_e9610f_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
