# Generated by Django 6.0.7 on 2026-09-21 10:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0009_driverprofile_latitude_driverprofile_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['scheduled_at'], name='rides_ride_schedul_eb2d24_idx'),
        ),
    ]
