# Generated by Django 6.0.7 on 2026-09-23 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0010_ride_scheduled_at_ride_rides_ride_schedul_eb2d24_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='booking_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('PAYMENT_FAILED', 'Payment Failed')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
